### ISSUE TITLE
Question: refresh token and secret

### ISSUE THREAD

**Issue by bitinn** [pillarjs/csrf#4]
If I understand correctly:

1. We should refresh token on *every request* and *every page* to mitigate BREACH (if we only refresh page with form, attacker can still guess content by repeatedly visit page without such protection)

2. Secret is per-user and if we store it on server session store, we can reuse it for a longtime, maybe a year, forever?

That's how `koa-csrf` appear to be using it.

I know create token is fast, only concern I have is refreshing token cause `Set-Cookie` every time, seem to be less than performant, any alternative available if I am to write my own csrf middleware?

**Comment by dougwilson** [comment]
The secret and token pair lasts forever. I know you made a lot of points, but a lot seem to be about the koa-csrf library, rather than this library.

Is there any other question from the above that I missed that is about this and not koa-csrf? (for example, this library does not do any set-cookie stuff and in fact does not even have access to req or res).

**Comment by jonathanong** [comment]
The token isn't set in the cookie, only the secret. A token is only set when the secret is created or the session decides to save the cookie again.

You shouldn't be resetting the secret often - there's no need to.

**Comment by bitinn** [comment]
Thx for your responses, I totally messed up my wording:

- Secret is in the session (cookie or session store, per-user).
- Token is created when we need to create a form, it's in the HTML, not cookie.
- Salt appends to token and comes back for validation.

I will close this now.
